Use bats/bats image for testing
inbucket/inbucket-community pull request #5
Opened 2023-01-03 11:21 UTC by supersven

dduportal/bats:0.4.0 is outdated and cannot be pulled from docker hub anymore.

This means that the tests were not run-able.

2023-01-03 12:53 UTC, cpanato requested changes
please bump the chart version

2023-01-03 15:40 UTC, supersven commented
> please bump the chart version

Sure :+1:

2023-01-16 10:04 UTC, supersven commented
@cpanato Friendly *ping* :smile_cat:

2023-01-16 16:42 UTC, cpanato approved these changes
lgtm

thanks

2023-01-16 16:43 UTC, merged