:sparkles: Split services between admin and mail
inbucket/inbucket-community pull request #6
Opened 2023-03-27 04:00 UTC by mikelorant

Split services to allow the admin interface to be managed independently from the mail receiving.

This allows for the web interface to have access controls (via the ingress) while still allowing open access to receive email on the SMTP or POP3 port.

2023-03-27 04:28 UTC, jhillyerd commented
cc @cpanato

2023-03-27 05:49 UTC, mikelorant commented
Unintentionally directed this to upstream instead of my own master. Not sure there is enough testing (still doing this locally) but will report back if there are problems.

2023-03-27 07:22 UTC, cpanato requested changes
thanks for this PR
Please sign the DCO and also you will need to update the tests

2023-04-08 05:35 UTC, closed without merging

2023-04-08 05:35 UTC, mikelorant commented
Will rework this as I am not happy with how it is implemented.